### PR TITLE
Fix `inverse_rle` with negative lengths

### LINKED ISSUE #851: Buffer overflow using `inverse_rle`
https://github.com/JuliaStats/StatsBase.jl/blob/42feefb84aa81d9f8918500ecf159dbee5bcb91f/src/misc.jl#L71-L86

If `lens` contains a negative element, the allocated array `r` will be smaller than needed and buffer overflow will occur. This will sometimes result in an access violation.

```julia
julia> using StatsBase

julia> inverse_rle(1:3, [-2,1,3])
2-element
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1ee9e7b -- jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1217
in expression starting at none:0       
jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1217
jl_gc_alloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_gc_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3290  
_new_array_ at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:127 [inlined]
_new_array at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:193 
[inlined]
jl_alloc_array_1d at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:441
[...]
```

Simple fix could be to add a check for negative elements.

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #851.

### CODE REVIEW

File: src/misc.jl [hunk 1]
```diff
@@ -60,7 +60,7 @@ run lengths.
 function inverse_rle(vals::AbstractVector{T}, lens::AbstractVector{<:Integer}) where T
     m = length(vals)
     length(lens) == m || raise_dimerror()
-
+    all(>=(0), lens) || throw(ArgumentError("lengths must be non-negative"))
```
Comment (devmotion) [inline src/misc.jl:63]: Is there a specific reason to support `0`? I would have assumed that a valid run-length encoding does not contain values with length `0`.
```suggestion
    all(>(0), lens) || throw(ArgumentError("lengths must be positive"))
```

I'm also a bit surprised that tests do not error on Julia 1.0 since
```julia
help?> >=(0)
  >=(x)

  Create a function that compares its argument to x using >=, i.e. a function equivalent to y -> y >= x. The returned function is of type
  Base.Fix2{typeof(>=)}, which can be used to implement specialized methods.

  │ Julia 1.2
  │
  │  This functionality requires at least Julia 1.2.

help?> >(0)
  >(x)

  Create a function that compares its argument to x using >, i.e. a function equivalent to y -> y > x. The returned function is of type
  Base.Fix2{typeof(>)}, which can be used to implement specialized methods.

  │ Julia 1.2
  │
  │  This functionality requires at least Julia 1.2.
````

Comment (ararslan) [reply src/misc.jl:63]: > Is there a specific reason to support 0?

Not really but it doesn't hurt to support IMO and may possibly be convenient to someone at some point ¯\\\_(ツ)\_/¯

> I'm also a bit surprised that tests do not error on Julia 1.0 since [...]

Huh yeah, me too. Maybe it existed in 1.0 but was undocumented and/or didn't return a `Fix2`? I don't have 1.0 handy to check.

Comment (kritpetra) [reply src/misc.jl:63]: > Is there a specific reason to support `0`? I would have assumed that a valid run-length encoding does not contain values with length `0`.

I can definitely see how someone would want to programmatically create lists where some values can be skipped, e.g.
```julia
julia> r = 3
julia> startidx = [2,5,3]
julia> inverse_rle.(Ref(["A", "B", "C"]), ([i-1, r, max(0,8-i-r)] for i in startidx))
3-element Vector{Vector{String}}:
 ["A", "B", "B", "B", "C", "C", "C"]
 ["A", "A", "A", "A", "B", "B", "B"]
 ["A", "A", "B", "B", "B", "C", "C"]
```

Comment (nalimilan) [reply src/misc.jl:63]: I agree allowing zeros can be useful.

I've checked Julia 1.0, `>(0)` and `>=(0)` work thanks to Compat.jl.

File: src/misc.jl [hunk 2]
```diff
@@ -60,7 +60,7 @@ run lengths.
...
     r = Vector{T}(undef, sum(lens))
     p = 0
     @inbounds for i = 1 : m
```
Comment (nalimilan) [inline src/misc.jl:66]: How about doing `j >= 0 || throw(ArgumentError("lengths must be positive"))` here instead, to avoid going over the vector twice?

Comment (ararslan) [reply src/misc.jl:66]: I guess the tradeoff is iterate twice or iterate once but always allocate a (potentially large) array and branch at each iteration. I suspect iterating twice would be more efficient but I haven't actually benchmarked or anything like that.

Comment (nalimilan) [reply src/misc.jl:66]: Allocating before throwing an error doesn't  sound like a problem to me as it shouldn't happen in valid code. As for branching on each iteration, given that there's already a branch I imagine it won't make the loop slower. But not a big deal anyway.

**Review by nalimilan — APPROVED** [review]

File: src/misc.jl (hunk 2 above)
Comment (ararslan) [reply src/misc.jl:66]: > Allocating before throwing an error doesn't sound like a problem to me as it shouldn't happen in valid code.

Ha yeah, fair point.

> As for branching on each iteration, given that there's already a branch I imagine it won't make the loop slower.

Oh you're right, for some reason the `while` loop didn't register to me as branching.

I'm happy to change if you prefer, I don't really care either way.

Comment (nalimilan) [reply src/misc.jl:66]: Maybe change it if you feel like it, otherwise it's fine.

File: src/misc.jl [hunk 3]
```diff
@@ -65,6 +65,7 @@ function inverse_rle(vals::AbstractVector{T}, lens::AbstractVector{<:Integer}) w
     p = 0
```
[the remark this answers is not in the document]
Comment (ararslan) [reply src/misc.jl:67]: Added a check on the sum per your suggestion since we need to compute the sum anyway in order to initialize the output array.
